# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-15119-amin-maky-ROG/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7vx485tffg1157-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/axi-f14341c32cf56c49/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include
  } -define {TARGET_CV32A6_IMAC_SV32 TARGET_FPGA TARGET_SYNTHESIS TARGET_VIVADO TARGET_XILINX} /run/media/amin-maky/Apps/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -sv -include {
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/axi-f14341c32cf56c49/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include
  } -define {TARGET_CV32A6_IMAC_SV32 TARGET_FPGA TARGET_SYNTHESIS TARGET_VIVADO TARGET_XILINX} {
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/config_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/cv32a6_imac_sv32_config_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/riscv_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/ariane_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/cf_math_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/acc_dispatcher.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/aes_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/aes.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/alu.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/alu_wrapper.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/amo_buffer.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/ariane_regfile_ff.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/ariane_regfile_fpga.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/axi-f14341c32cf56c49/src/axi_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/axi_adapter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/axi_shim.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/bht.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/bht2lvl.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/branch_unit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/btb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/build_config_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/std_cache_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cache_ctrl.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/commit_stage.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/compressed_decoder.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/defs_div_sqrt_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/control_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/controller.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/counter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/csr_buffer.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/csr_regfile.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/wt_cache_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_accel_first_pass_decoder_stub.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_fifo_v3.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include/dummy_l15_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_hpdcache_wrapper.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_icache.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_mmu/cva6_mmu.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_mmu/cva6_ptw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_rvfi_probes.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_mmu/cva6_shared_tlb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6_mmu/cva6_tlb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cvxif_compressed_if_driver.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cvxif_fu.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cvxif_issue_register_commit_if_driver.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/decoder.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/delta_counter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/div_sqrt_top_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/ex_stage.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/exp_backoff.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/cvw/fma/fmalza.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_cast_multi.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_classifier.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_multi.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_th_32.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_divsqrt_th_64_multi.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_fma.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_fma_multi.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_noncomp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_block.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_fmt_slice.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_opgroup_multifmt_slice.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_rounding.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/src/fpnew_top.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/fpu_wrap.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/frontend.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cbuf.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_bin_encoder.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_pkg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_ecc_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_ecc_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_ecc_1rw.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/id_stage.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/instr_queue.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/instr_realign.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/instr_scan.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/issue_read_operands.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/issue_stage.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/iteration_div_sqrt_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lfsr.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lfsr_8bit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/load_store_unit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/load_unit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/lsu_bypass.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/lzc.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/miss_handler.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/mult.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/multiplier.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/norm_div_sqrt_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/nrbd_nrsc_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/perf_counters.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/pmp/src/pmp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/pmp/src/pmp_data_if.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/pmp/src/pmp_entry.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/popcount.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpu_div_sqrt_mvp-dd98d4eaba0b805e/hdl/preprocess_mvp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_36_29_dec.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_36_29_enc.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_39_32_dec.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_39_32_enc.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_55_48_dec.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_55_48_enc.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_72_64_dec.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc/prim_secded_72_64_enc.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/frontend/ras.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/raw_checker.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/rr_arb_tree.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/scoreboard.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/serdiv.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/shift_reg.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/shift_reg_gated.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/spill_register.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/spill_register_flushable.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util/sram.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util/sram_cache.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/std_cache_subsystem.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/std_nbdcache.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/store_buffer.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/store_unit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_arbiter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_arbiter_flushable.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_demux.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/stream_mux.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/tag_cmp.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util/tc_sram_fpga_wrapper.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/src/unread.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_axi_adapter.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_cache_subsystem.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_dcache.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_dcache_mem.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_dcache_missunit.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cva6.sv
    }
      rt::read_verilog -include {
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/axi-f14341c32cf56c49/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/common_cells-7e395bb92335c3c4/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/common/local/util
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/include
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/ecc
    /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/core/include
  } -define {TARGET_CV32A6_IMAC_SV32 TARGET_FPGA TARGET_SYNTHESIS TARGET_VIVADO TARGET_XILINX} {
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
      /run/media/amin-maky/LinuxFiles/Prj/CVA6/cv32a6_imac_sv32/cva6/.bender/git/checkouts/fpnew-e0f7063a95eee5e4/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
    }
      rt::read_vhdl -lib xpm /run/media/amin-maky/Apps/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cva6
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-15119-amin-maky-ROG/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
